In [1]:
import pandas as pd
import pandas_profiling as pp
from restaurantsFinder import restaurantFinder
import numpy as np
np.random.seed(1)
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/restaurants.csv')
df.head()

name  xcor  ycor  score  foodPrice
0     0    38     1      9         22
1     1    13    78      8         22
2     2    73     7      1         36
3     3    10    53      4         22
4     4    76    86      5         17

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       100 non-null    int64
 1   xcor       100 non-null    int64
 2   ycor       100 non-null    int64
 3   score      100 non-null    int64
 4   foodPrice  100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB


## EDA

In [4]:
# pp.ProfileReport(df)

## Code Implementation

In [5]:
arr = np.array(df)
restaurantFinder = restaurantFinder(arr,"greedy",500,240)

[]
[ 0 38  1  9 22]
[ 1 13 78  8 22]
[ 2 73  7  1 36]
[ 3 10 53  4 22]
[ 4 76 86  5 17]
[ 5  6 71  3 33]
[ 6 80  3  1 49]
[ 7 65 77  4 22]
[ 8 17 92  6 48]
[ 9  2 22  2 37]
[10 77 76  3 15]
[11 72  8  5 44]
[12  7 78  4 43]
[13 26 73  1 36]
[14 51 76  7 15]
[15 21 77  1 19]
[16 19 44  8 35]
[17 85 21  3 37]
[18 12 31  9 11]
[19 29 37  4 28]
[20 30  8  1 40]
[21 15 46  9 42]
[22 51 69  5 36]
[23 69 58  3 30]
[24 88 83 10 40]
[25 88 97  1 49]
[26 95 14  4 10]
[27 97 11  9 32]
[28 87 24  2 44]
[29 14 82  5 13]
[30 10  8  4 16]
[31  8 25  4 22]
[32 64 75  7 49]
[33 62 93  8 48]
[34 23 21  4 29]
[35 58 33  6 16]
[36  2 13  4 23]
[37  1 66  3 46]
[38 61 95  5 33]
[39 82 61  5 32]
[40  9 25  1 12]
[41 89 83  4 38]
[42 14 98  4 41]
[43 48  3  9 19]
[44 73 93  4 34]
[45 31 99  6 39]
[46 72 11  7 22]
[47  4 55  8 28]
[48 71 97  6 21]
[49 22 83  2 46]
[50 50 87  8 26]
[51 58 71  1 40]
[52  4 67  3 30]
[53 69 72  9 45]
[54 25 49  3 27]
[55 44 55  2 12]
[56 77 16  5 31]
[57 27  6  1 39]
[58 53 18  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
print(restaurantFinder.find(5))

[ 5  6 71  3 33]


In [ ]:
restaurantFinder.runMethod()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()